# SITE CONFIGURATION
#baseurl: /vulkan-guide
url: "//vkguide.dev"
title: Vulkan Guide # site's title
description: "Brand new guide to vulkan graphics programming" # used by search engines

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Vulkan Spec":
    - "https://www.khronos.org/registry/vulkan/specs/1.2-extensions/html/chap2.html#introduction"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 Victor Blanco. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: dark

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
#ga_tracking: UA-2709176-10

plugins:
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false